### ISSUE TITLE
Using with ACT

### ISSUE THREAD

**Issue by Poldovico** [ackwell/BrowserHost#17]
Sorry about the silly question, but I can't find any documentation on how to use this with ACT.
The description makes me think this can replace OverlayPlugin, but I can't make it work.

**Comment by DAOWAce** [comment]
If you didn't get your answer or figure out how to do it, here's an excerpt from this thread: https://forums.advancedcombattracker.com/discussion/263/are-there-any-skins-that-allow-me-to-run-ffxiv-act-in-full-screen

> But in this case, I believe your only option is the BrowserHost plugin for XL launcher.  This will inject a web browser into the FFXIV game process, similar to Steam or some FPS counter.  Once you have a browser in your game, generate a URL from OverlayPlugin and use it with the game's process.  (you still need OverlayPlugin running WSServer, but without an overlay active)

**Comment by Poldovico** [comment]
Thank you very much!
I thought the Dalamud plugin would make OverlayPlugin reduntant, but instead they work together.
